name: Auto Merge PRs

on:
  pull_request:
    types:
      - labeled

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "${{github.event.pull_request.labels}}"
      - name: Auto-merge pull requests that pass tests
        uses: "pascalgn/automerge-action@4536e8847eb62fe2f0ee52c8fa92d17aa97f932f"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: squash
