name: CI (PR)

on:
  repository_dispatch:
    types: 
      - trigger-ci

env:
  CONTENT_REPO: "https://github.com/box/developer.box.com.git#en"

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      with: 
        ref: ${{ github.event.client_payload.ref }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Lint the content
      run: |
        yarn install
        yarn test
